# Generated by Django 6.0.1 on 2026-01-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
