# Generated by Django 6.0.1 on 2026-01-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_contact_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
